### ISSUE TITLE
node v4 support?

### ISSUE THREAD

**Issue by wdalmut** [binarysec/node-tuntap#1]
Hi,

do you think to extends this project to node v4?

The build process fail on node v4 but is working on v0.12.

Bests
Walter

**Comment by mykiimike** [comment]
Hi,

Yes we should. 
Could you paste here your build process (failing) output ?

Thanks
Michael

**Comment by wdalmut** [comment]
Of course i can,

here is my error with `node`: 

``` sh
12:04 $ node -v
v4.4.3
```

And `node-gyp`:

``` sh
12:05 $ node-gyp -v
v3.3.1
```

The compile stacktrace

``` sh
12:04 $ CPLUS_INCLUDE_PATH=~/node/include/ C_INCLUDE_PATH=~/node/include/ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/walter/node-v4.4.3-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/walter/git/node-tuntap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/walter/node-v4.4.3-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/walter/.node-gyp/4.4.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/walter/.node-gyp/4.4.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/walter/node-v4.4.3-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/walter/git/node-tuntap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/walter/git/node-tuntap/build'
  CXX(target) Release/obj.target/tuntap/src/module.o
  CXX(target) Release/obj.target/tuntap/src/tuntap.o
../src/tuntap.cc: In member function ‘void Tuntap::do_read()’:
../src/tuntap.cc:638:75: error: no matching function for call to ‘New(v8::Isolate*&, const char*, int&)’
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
../src/tuntap.cc:638:75: error: invalid conversion from ‘int’ to ‘node::encoding’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
../src/tuntap.cc:638:75: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
../src/tuntap.cc:641:83: error: no matching function for call to ‘New(v8::Isolate*&, const char*, int)’
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 2, ret - 2);
                                                                                   ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
../src/tuntap.cc:641:80: error: invalid conversion from ‘int’ to ‘node::encoding’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 2, ret - 2);
                                                                                ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
../src/tuntap.cc:641:71: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 2, ret - 2);
                                                                       ^
../src/tuntap.cc:646:83: error: no matching function for call to ‘New(v8::Isolate*&, const char*, int)’
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 3, ret - 3);
                                                                                   ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
../src/tuntap.cc:646:80: error: invalid conversion from ‘int’ to ‘node::encoding’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 3, ret - 3);
                                                                                ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
../src/tuntap.cc:646:71: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff + 3, ret - 3);
                                                                       ^
../src/tuntap.cc:649:75: error: no matching function for call to ‘New(v8::Isolate*&, const char*, int&)’
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
../src/tuntap.cc:649:75: error: invalid conversion from ‘int’ to ‘node::encoding’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
In file included from ../src/module.hh:26:0,
                 from ../src/tuntap.cc:22:
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/walter/.node-gyp/4.4.3/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
../src/tuntap.cc:649:75: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   ret_buff = node::Buffer::New(isolate, (const char*) this->read_buff, ret);
                                                                           ^
tuntap.target.mk:90: recipe for target 'Release/obj.target/tuntap/src/tuntap.o' failed
make: *** [Release/obj.target/tuntap/src/tuntap.o] Error 1
make: Leaving directory '/home/walter/git/node-tuntap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/walter/node-v4.4.3-linux-x64/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/home/walter/node-v4.4.3-linux-x64/bin/node" "/home/walter/node/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/walter/git/node-tuntap
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by wdalmut** [comment]
Thanks! :dancers:
